#!/bin/bash
#
# Submits a job to Moab.
#
# Requires the following environment variables to be defined:
#
#   APPNAME             mutatee base filename
#   TAG                 short (filename-safe) description of trial
#
# Optional environment variables:
#
#   WALLTIME            walltime to request from cluster (default: 12h)
#

export ROOT_PATH="$HOME"
export JOBSCRIPT="$ROOT_PATH/jobs/run_trial"

function startjob {

    # check for required environment variables
    if [ -z "$APPNAME" ]; then
        echo "ERROR: APPNAME must be defined!"
        exit 1
    fi
    if [ -z "$TAG" ]; then
        echo "ERROR: TAG must be defined!"
        exit 1
    fi

    if [ -z "$WALLTIME" ]; then
        export WALLTIME="12:00:00"
    fi

    export OUTFILE="$ROOT_PATH/log/$APPNAME-$TAG.out"

    # to run locally (for testing)
    #$JOBSCRIPT

    # to run on grid
    echo "rm -f $OUTFILE"
    rm -f $OUTFILE
    echo "msub -N $APPNAME-$TAG -l walltime=$WALLTIME -o $OUTFILE $JOBSCRIPT"
    msub -N $APPNAME-$TAG -l walltime=$WALLTIME -o $OUTFILE $JOBSCRIPT

}

