#!/bin/bash

TAG=`date +%Y_%m_%d-%H_%M_%S`
JOB_PATH=`pwd`
WALLTIME=$1
CMD=$2
set -- $CMD
NAME=$1
#touch $1
#OUTFILE=`readlink -f $1`

ROOT_PATH="$HOME"
JOBSCRIPT="$ROOT_PATH/jobs/tmp/job_$TAG"
#OUTFILE="$ROOT_PATH/log/job_$TAG.out"
OUTFILE="$JOB_PATH/job_$TAG.out"

echo "#!/bin/bash" >$JOBSCRIPT
echo "#MSUB -N $NAME" >>$JOBSCRIPT
echo "#MSUB -l nodes=1" >>$JOBSCRIPT
echo "#MSUB -l partition=atlas" >>$JOBSCRIPT
echo "#MSUB -l walltime=$WALLTIME" >>$JOBSCRIPT
echo "#MSUB -q pbatch" >>$JOBSCRIPT
echo "#MSUB -V" >>$JOBSCRIPT
echo "#MSUB -j oe" >>$JOBSCRIPT
echo "#MSUB -d $JOB_PATH" >>$JOBSCRIPT
echo "#MSUB -o $OUTFILE" >>$JOBSCRIPT
echo "" >>$JOBSCRIPT
echo "$CMD" >>$JOBSCRIPT

cat $JOBSCRIPT

#echo "msub $JOBSCRIPT"
msub $JOBSCRIPT

