#!/bin/bash

source $HOME/jobs/msub_func

export APPNAME="dealII"

export TAG="d_cancel-1"
export INST_PARAMS="-i --count-inst --detect-cancel"
export MUTANT_PARAMS="1"
startjob

export TAG="ptr_double-1"
#export TAG="ptr_double-1-g"
export INST_PARAMS="-i --pointer-double -r"
#export INST_PARAMS="-i --pointer-double -r -g"
export MUTANT_PARAMS="1"
#export MUTANT_PARAMS="1 >/p/lscratchc/lam26/dealII_debug_out"
startjob

export TAG="ptr_single-1"
export INST_PARAMS="-i --pointer-single -r"
export MUTANT_PARAMS="1"
startjob

