#!/bin/bash

source $HOME/jobs/msub_func

export APPNAME="milc"
export COPY_FILES="milc.in.short"

#export TAG="d_cancel-short"
#export INST_PARAMS="-i --count-inst --detect-cancel"
#export MUTANT_PARAMS="<milc.in.short"
#startjob

#export TAG="ptr_double-short"
export TAG="ptr_double-short-g"
#export INST_PARAMS="-i --pointer-double -r"
export INST_PARAMS="-i --pointer-double -r -g"
#export MUTANT_PARAMS="<milc.in.short"
export MUTANT_PARAMS="<milc.in.short >/p/lscratchc/lam26/milc_debug_out"
startjob

#export TAG="ptr_single-short"
#export INST_PARAMS="-i --pointer-single -r"
#export MUTANT_PARAMS="<milc.in.short"
#startjob

