#!/bin/bash

source $HOME/jobs/msub_func

export APPNAME="soplex"
export COPY_FILES="soplex.input.short"

#export WALLTIME=1:00:00

export TAG="d_cancel-short"
export INST_PARAMS="-i --count-inst --detect-cancel"
export MUTANT_PARAMS="soplex.input.short"
startjob

#export WALLTIME=2:00:00

export TAG="ptr_double-short"
#export TAG="ptr_double-short-g"
export INST_PARAMS="-i --pointer-double -r"
#export INST_PARAMS="-i --pointer-double -r -g"
export MUTANT_PARAMS="soplex.input.short"
#export MUTANT_PARAMS="soplex.input.short >/p/lscratchc/lam26/soplex_debug_out"
startjob

export TAG="ptr_single-short"
export INST_PARAMS="-i --pointer-single -r"
export MUTANT_PARAMS="soplex.input.short"
startjob

