#!/bin/bash

source $HOME/jobs/msub_func

export APPNAME="povray"
export COPY_FILES="test.ini test.pov include"

#export TAG="d_cancel-test"
#export INST_PARAMS="-i --count-inst --detect-cancel"
#export MUTANT_PARAMS="test.ini +Itest.pov +Linclude +Otest.tga"
#startjob

#export TAG="ptr_double-test"
#export INST_PARAMS="-i --pointer-double -r"
#export MUTANT_PARAMS="test.ini +Itest.pov +Linclude +Otest.tga"
#startjob

#export TAG="ptr_double-test-g"
#export INST_PARAMS="-i --pointer-double -r -g"
#export MUTANT_PARAMS="test.ini +Itest.pov +Linclude +Otest.tga >/p/lscratchc/lam26/povray_debug_out"
#startjob

export TAG="ptr_single-test"
export INST_PARAMS="-i --pointer-single -r"
export MUTANT_PARAMS="test.ini +Itest.pov +Linclude +Otest.tga"
startjob

