#!/bin/bash

source $HOME/jobs/msub_func

export APPNAME="quake"
export COPY_FILES="quake.in.short"

export TAG="d_cancel-short"
export INST_PARAMS="-i --count-inst --detect-cancel"
export MUTANT_PARAMS="<quake.in.short"
startjob

export TAG="ptr_double-short"
export INST_PARAMS="-i --pointer-double -r"
export MUTANT_PARAMS="<quake.in.short"
startjob

export TAG="ptr_single-short"
export INST_PARAMS="-i --pointer-single -r"
export MUTANT_PARAMS="<quake.in.short"
startjob

