#!/bin/sh
#
# SAMPLE DRIVER SCRIPT
#

# setup
binary=$1
tmp_file=stdout.tmp

# start timing
t_start=`date +%s`

# MODIFY THIS: run binary
$binary >$tmp_file
exit_code=$?

# stop timing
t_stop=`date +%s`

# calculate runtime
runtime=$(expr $t_stop - $t_start)

# MODIFY THIS: check verification
status="pass"
if [ $exit_code -ne 0 ]; then
    status="error"
else
    check=`grep "[^N]SUCCESSFUL" $tmp_file`
    if [ -z "$check" ]; then
        status="fail"
    fi
fi

# MODIFY THIS: calculate error
error="0.0e0"

# print output
echo "status:  $status"
echo "time:    $runtime"
echo "error:   $error"

# cleanup
rm -f $tmp_file


