#!/bin/bash
#
# SAMPLE DRIVER SCRIPT
#

# setup
binary=$1
tmp_file=stdout.tmp

# start timing
t_start=`date +%s`

# MODIFY THIS: run binary
$binary >$tmp_file

# stop timing
t_stop=`date +%s`

# calculate runtime
runtime=$(expr $t_stop - $t_start)

# MODIFY THIS: check verification
passed=`grep "[^N]SUCCESSFUL" $tmp_file`
if [ -z "$passed" ]; then
    status="fail"
else
    status="pass"
fi

# MODIFY THIS: calculate error
error="0.0e0"

# print output
echo "status:  $status"
echo "time:    $runtime"
echo "error:   $error"

# cleanup
rm -f $tmp_file


