#!/bin/bash

# copy file(s) to current folder
cp /full/path/to/main.cpp .

# run each file through TypeForge
typeforge --spec-file=$1 main.cpp

# compile to executable named "mutant"
g++ -g -o mutant rose_main.cpp

