#!/usr/bin/ruby
#
# with one argument, outputs sorted instructions from config file
# with two arguments, compares instructions from two config files
#

fout1 = File.new("tmp1.txt","w")
IO.foreach(ARGV[0]) do |line|
    if line =~ /^\^(.).*INSN #\d+: (0x[0-9A-Fa-f]+) \"(.+)\"/ then
        fout1.puts "#{$1} #{$2} #{$3}"
    end
end
fout1.close
system('sort tmp1.txt >tmp1s.txt')

if ARGV.size > 1 then
    fout2 = File.new("tmp2.txt","w")
    IO.foreach(ARGV[1]) do |line|
        if line =~ /^\^(.).*INSN #\d+: (0x[0-9A-Fa-f]+) \"(.+)\"/ then
            fout2.puts "#{$1} #{$2} #{$3}"
        end
    end
    fout2.close
    system('sort tmp2.txt >tmp2s.txt')
    system('diff tmp1s.txt tmp2s.txt')
else
    puts "here"
    system('cat tmp1s.txt')
end

File.delete('tmp1.txt')  if File.exists?('tmp1.txt')
File.delete('tmp1s.txt') if File.exists?('tmp1s.txt')
File.delete('tmp2.txt')  if File.exists?('tmp2.txt')
File.delete('tmp2s.txt') if File.exists?('tmp2s.txt')

