#!/usr/bin/ruby -W0

printNextLine = false

if ARGV.size < 1
    puts "usage: extract_tramps <fpout> [<address>]"
    exit
end

filename = ARGV[0]
if ARGV.size > 1
    address = ARGV[1].hex
else
    address = 0x0
end

IO.foreach(filename) do |line|
    if printNextLine
        puts line
        printNextLine = false
    end
    if line =~ /built binary blob at (0x[0-9a-fA-F]+) \[size=([0-9]+)\]/
        start_addr = $1
        end_addr = "0x#{($1.hex + $2.to_i).to_s(16)}"
        if address == 0x0 || (address >= start_addr.hex && address <= end_addr.hex)
            puts
            puts line
            cmd = "xed -i mutant -64 -I -as #{start_addr} -ae #{end_addr}"
            puts cmd
            IO.popen(cmd).each_line do |asmline|
                if !(asmline =~ /^#/)
                    puts asmline
                end
            end
            printNextLine = true
        end
    end
end

