#!/bin/sh

BACKGROUND="y"
PROFILER="n"

VMOPTS="-Xmx1024M"

if [ "$PROFILER" = "y" ]; then
    VMOPTS="$VMOPTS -Xrunhprof:cpu=samples,interval=20,depth=5"
fi

SCRIPT_PATH=$(cd $(dirname $0); pwd -P)

if [ "$BACKGROUND" = "y" ]; then
    java $VMOPTS -jar $SCRIPT_PATH/../viewer/fpconfed.jar $@ &
else
    java $VMOPTS -jar $SCRIPT_PATH/../viewer/fpconfed.jar $@
fi

