#!/usr/bin/env bash
#
# Runs editor UI with a few supported command-line parameters.
# (Basically just a wrapper for launching the JAR file)
#

BACKGROUND="y"
PROFILER="n"

VMOPTS="-Xmx1024M"

if [ "$PROFILER" = "y" ]; then
    VMOPTS="$VMOPTS -Xrunhprof:cpu=samples,interval=20,depth=5"
fi

# get the path of this script, regardless of any symlinks
#   (from https://stackoverflow.com/a/246128)
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_PATH="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

if [ "$BACKGROUND" = "y" ]; then
    java $VMOPTS -jar $SCRIPT_PATH/../viewer/fpconfed.jar $@ &
else
    java $VMOPTS -jar $SCRIPT_PATH/../viewer/fpconfed.jar $@
fi

