#!/usr/bin/env bash
#
# Runs viewer UI with a few supported command-line parameters.
# (Basically just a wrapper for launching the JAR file)
#

BACKGROUND="y"

for p in $@; do
    if [ "$p" = "-c" ]; then
        BACKGROUND="n"
    fi
    if [ "$p" = "-i" ]; then
        BACKGROUND="n"
    fi
    if [ "$p" = "-s" ]; then
        BACKGROUND="n"
    fi
done

SCRIPT_PATH=$(cd $(dirname $0); pwd -P)

if [ "$BACKGROUND" = "y" ]; then
    java -Xmx1024M -jar $SCRIPT_PATH/../viewer/fpview.jar $@ &
else
    java -Xmx1024M -jar $SCRIPT_PATH/../viewer/fpview.jar $@
fi

