#!/bin/sh

BACKGROUND="y"

for p in $@; do
    if [ "$p" = "-c" ]; then
        BACKGROUND="n"
    fi
    if [ "$p" = "-i" ]; then
        BACKGROUND="n"
    fi
    if [ "$p" = "-s" ]; then
        BACKGROUND="n"
    fi
done

SCRIPT_PATH=$(cd $(dirname $0); pwd -P)

if [ "$BACKGROUND" = "y" ]; then
    java -Xmx1024M -jar $SCRIPT_PATH/../viewer/fpview.jar $@ &
else
    java -Xmx1024M -jar $SCRIPT_PATH/../viewer/fpview.jar $@
fi

