#!/bin/bash


#EXEPATH=$DYNINST_ROOT/craft/utils/iprof

# find path of this script
pushd `dirname $0` >/dev/null
EXEPATH=`pwd`
popd >/dev/null

$EXEPATH/mutator $@ &>fpinst.txt
./mutant &>output.txt
rm -f libc.so.6 libm.so.6
$EXEPATH/analysis.rb output.txt &>analysis.txt

montage -geometry +4+4 -tile 1x2 all-itype.png fp-itype.png composite-itype.png
montage -geometry +4+4 -tile 1x4 all-memacc.png fp-memacc.png fp-dtype.png fpmov-dtype.png composite-memacc_dtype.png

